name: release test

on:
  push:
  pull_request:

jobs:
  build_x86_64_unknown_linux_musl:
    runs-on: ubuntu-latest
    name: Build x86_64-unknown-linux-musl target
    steps:
      - uses: actions/checkout@v2
      - name: Run Build Script
        run: |
          pushd
          cd crates/web5_cli/build/x86_64_unknown_linux_musl
          ./build
          popd
          cp target/x86_64-unknown-linux-musl/release/web5_cli web5_cli-x86_64-unknown-linux-musl
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: web5-x86_64-linux-musl
          path: web5_cli-x86_64-unknown-linux-musl
