name: Build web5_cli release

on:
  release: {}

jobs:
  build_aarch64_apple_darwin:
    runs-on: macos-latest
    name: Build aarch64-apple-darwin target
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup toolchain install stable
      - name: cargo build
        run: |
          cargo build --target aarch64-apple-darwin --release --package web5_cli
          cp -v target/aarch64-apple-darwin/release/web5_cli web5_cli-aarch64-apple-darwin
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: web5_cli-aarch64-apple-darwin
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build_x86_64_apple_darwin:
    runs-on: macos-12
    name: Build x86_64-apple-darwin target
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup toolchain install stable
      - name: cargo build
        run: |
          cargo build --target x86_64-apple-darwin --release --package web5_cli --features x86_64_apple_darwin
          cp -v target/x86_64-apple-darwin/release/web5_cli web5_cli-x86_64-apple-darwin
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: web5_cli-x86_64-apple-darwin
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build_x86_64_unknown_linux_gnu:
    runs-on: ubuntu-latest
    name: Build x86_64-unknown-linux-gnu target
    steps:
      - uses: actions/checkout@v2
      - name: cargo build
        run: |
          cargo build --target x86_64-unknown-linux-gnu --release --package web5_cli
          cp -v target/x86_64-unknown-linux-gnu/release/web5_cli web5_cli-x86_64-unknown-linux-gnu
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: web5_cli-x86_64-unknown-linux-gnu
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build_x86_64_unknown_linux_musl:
    runs-on: ubuntu-latest
    name: Build x86_64-unknown-linux-musl target
    steps:
      - uses: actions/checkout@v2
      - name: cargo build
        run: |
          cargo build --target x86_64-unknown-linux-musl --release --package web5_cli
          mv release/web5_cli ../../../../web5_cli-x86_64-unknown-linux-musl
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: web5_cli-x86_64-unknown-linux-musl
          repo-token: ${{ secrets.GITHUB_TOKEN }}
